
package nl.se42.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionService", targetNamespace = "http://webservice.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns nl.se42.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.RegisterResponse")
    @Action(input = "http://webservice.auction/AuctionService/registerRequest", output = "http://webservice.auction/AuctionService/registerResponse")
    public User register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns nl.se42.client.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.NewBidResponse")
    @Action(input = "http://webservice.auction/AuctionService/newBidRequest", output = "http://webservice.auction/AuctionService/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Money arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns nl.se42.client.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.OfferItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/offerItemRequest", output = "http://webservice.auction/AuctionService/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns nl.se42.client.Money
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoneyObject", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetMoneyObject")
    @ResponseWrapper(localName = "getMoneyObjectResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetMoneyObjectResponse")
    @Action(input = "http://webservice.auction/AuctionService/getMoneyObjectRequest", output = "http://webservice.auction/AuctionService/getMoneyObjectResponse")
    public Money getMoneyObject(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<nl.se42.client.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetAllUsersResponse")
    @Action(input = "http://webservice.auction/AuctionService/getAllUsersRequest", output = "http://webservice.auction/AuctionService/getAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns nl.se42.client.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/getItemRequest", output = "http://webservice.auction/AuctionService/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns nl.se42.client.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHighestBidForItem", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetHighestBidForItem")
    @ResponseWrapper(localName = "getHighestBidForItemResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetHighestBidForItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/getHighestBidForItemRequest", output = "http://webservice.auction/AuctionService/getHighestBidForItemResponse")
    public Bid getHighestBidForItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clearDatabase", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.ClearDatabase")
    @ResponseWrapper(localName = "clearDatabaseResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.ClearDatabaseResponse")
    @Action(input = "http://webservice.auction/AuctionService/clearDatabaseRequest", output = "http://webservice.auction/AuctionService/clearDatabaseResponse")
    public void clearDatabase();

    /**
     * 
     * @param arg0
     * @return
     *     returns nl.se42.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.LoginResponse")
    @Action(input = "http://webservice.auction/AuctionService/loginRequest", output = "http://webservice.auction/AuctionService/loginResponse")
    public User login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<nl.se42.client.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOfferedItemsForUser", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetOfferedItemsForUser")
    @ResponseWrapper(localName = "getOfferedItemsForUserResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetOfferedItemsForUserResponse")
    @Action(input = "http://webservice.auction/AuctionService/getOfferedItemsForUserRequest", output = "http://webservice.auction/AuctionService/getOfferedItemsForUserResponse")
    public List<Item> getOfferedItemsForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.RevokeItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/revokeItemRequest", output = "http://webservice.auction/AuctionService/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<nl.se42.client.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.FindItemByDescriptionResponse")
    @Action(input = "http://webservice.auction/AuctionService/findItemByDescriptionRequest", output = "http://webservice.auction/AuctionService/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAmountOfferedItemsForUser", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetAmountOfferedItemsForUser")
    @ResponseWrapper(localName = "getAmountOfferedItemsForUserResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetAmountOfferedItemsForUserResponse")
    @Action(input = "http://webservice.auction/AuctionService/getAmountOfferedItemsForUserRequest", output = "http://webservice.auction/AuctionService/getAmountOfferedItemsForUserResponse")
    public int getAmountOfferedItemsForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns nl.se42.client.Category
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryObject", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetCategoryObject")
    @ResponseWrapper(localName = "getCategoryObjectResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.GetCategoryObjectResponse")
    @Action(input = "http://webservice.auction/AuctionService/getCategoryObjectRequest", output = "http://webservice.auction/AuctionService/getCategoryObjectResponse")
    public Category getCategoryObject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns nl.se42.client.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItemWithPainter", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.OfferItemWithPainter")
    @ResponseWrapper(localName = "offerItemWithPainterResponse", targetNamespace = "http://webservice.auction/", className = "nl.se42.client.OfferItemWithPainterResponse")
    @Action(input = "http://webservice.auction/AuctionService/offerItemWithPainterRequest", output = "http://webservice.auction/AuctionService/offerItemWithPainterResponse")
    public Item offerItemWithPainter(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Category arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
