
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionService", targetNamespace = "http://webservice.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.auction/", className = "mypackage.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.RegisterResponse")
    @Action(input = "http://webservice.auction/AuctionService/registerRequest", output = "http://webservice.auction/AuctionService/registerResponse")
    public User register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.auction/", className = "mypackage.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.LoginResponse")
    @Action(input = "http://webservice.auction/AuctionService/loginRequest", output = "http://webservice.auction/AuctionService/loginResponse")
    public User login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "newBid2", targetNamespace = "http://webservice.auction/", className = "mypackage.NewBid2")
    @ResponseWrapper(localName = "newBid2Response", targetNamespace = "http://webservice.auction/", className = "mypackage.NewBid2Response")
    @Action(input = "http://webservice.auction/AuctionService/newBid2Request", output = "http://webservice.auction/AuctionService/newBid2Response")
    public void newBid2(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://webservice.auction/", className = "mypackage.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/getItemRequest", output = "http://webservice.auction/AuctionService/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<mypackage.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOfferedItemsForUser", targetNamespace = "http://webservice.auction/", className = "mypackage.GetOfferedItemsForUser")
    @ResponseWrapper(localName = "getOfferedItemsForUserResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetOfferedItemsForUserResponse")
    @Action(input = "http://webservice.auction/AuctionService/getOfferedItemsForUserRequest", output = "http://webservice.auction/AuctionService/getOfferedItemsForUserResponse")
    public List<Item> getOfferedItemsForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clearDatabase", targetNamespace = "http://webservice.auction/", className = "mypackage.ClearDatabase")
    @ResponseWrapper(localName = "clearDatabaseResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.ClearDatabaseResponse")
    @Action(input = "http://webservice.auction/AuctionService/clearDatabaseRequest", output = "http://webservice.auction/AuctionService/clearDatabaseResponse")
    public void clearDatabase();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns mypackage.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://webservice.auction/", className = "mypackage.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.OfferItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/offerItemRequest", output = "http://webservice.auction/AuctionService/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://webservice.auction/", className = "mypackage.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.RevokeItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/revokeItemRequest", output = "http://webservice.auction/AuctionService/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns mypackage.Doekoes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoneyObject", targetNamespace = "http://webservice.auction/", className = "mypackage.GetMoneyObject")
    @ResponseWrapper(localName = "getMoneyObjectResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetMoneyObjectResponse")
    @Action(input = "http://webservice.auction/AuctionService/getMoneyObjectRequest", output = "http://webservice.auction/AuctionService/getMoneyObjectResponse")
    public Doekoes getMoneyObject(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://webservice.auction/", className = "mypackage.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetAllUsersResponse")
    @Action(input = "http://webservice.auction/AuctionService/getAllUsersRequest", output = "http://webservice.auction/AuctionService/getAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHighestBidForItem", targetNamespace = "http://webservice.auction/", className = "mypackage.GetHighestBidForItem")
    @ResponseWrapper(localName = "getHighestBidForItemResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetHighestBidForItemResponse")
    @Action(input = "http://webservice.auction/AuctionService/getHighestBidForItemRequest", output = "http://webservice.auction/AuctionService/getHighestBidForItemResponse")
    public Bid getHighestBidForItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns mypackage.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://webservice.auction/", className = "mypackage.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.NewBidResponse")
    @Action(input = "http://webservice.auction/AuctionService/newBidRequest", output = "http://webservice.auction/AuctionService/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Doekoes arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<mypackage.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://webservice.auction/", className = "mypackage.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.FindItemByDescriptionResponse")
    @Action(input = "http://webservice.auction/AuctionService/findItemByDescriptionRequest", output = "http://webservice.auction/AuctionService/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns mypackage.Category
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryObject", targetNamespace = "http://webservice.auction/", className = "mypackage.GetCategoryObject")
    @ResponseWrapper(localName = "getCategoryObjectResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetCategoryObjectResponse")
    @Action(input = "http://webservice.auction/AuctionService/getCategoryObjectRequest", output = "http://webservice.auction/AuctionService/getCategoryObjectResponse")
    public Category getCategoryObject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns mypackage.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItemWithPainter", targetNamespace = "http://webservice.auction/", className = "mypackage.OfferItemWithPainter")
    @ResponseWrapper(localName = "offerItemWithPainterResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.OfferItemWithPainterResponse")
    @Action(input = "http://webservice.auction/AuctionService/offerItemWithPainterRequest", output = "http://webservice.auction/AuctionService/offerItemWithPainterResponse")
    public Item offerItemWithPainter(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Category arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAmountOfferedItemsForUser", targetNamespace = "http://webservice.auction/", className = "mypackage.GetAmountOfferedItemsForUser")
    @ResponseWrapper(localName = "getAmountOfferedItemsForUserResponse", targetNamespace = "http://webservice.auction/", className = "mypackage.GetAmountOfferedItemsForUserResponse")
    @Action(input = "http://webservice.auction/AuctionService/getAmountOfferedItemsForUserRequest", output = "http://webservice.auction/AuctionService/getAmountOfferedItemsForUserResponse")
    public int getAmountOfferedItemsForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
